name: Demo CI/CD Pipeline
on: 
    push:
        branches:
            - main
      env:
    PP_NAME: '${{ github.repository }}' 
    REGISTRY: ghcr.io
 jobs: 
    build:
        name: Build & Publish Docker Image 
        runs-on: ubuntu-latest         
        jobs: 
    build:
        name: Build & Publish Docker Image 
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            jobs:
    build:
        name: Build & Publish Docker Image
        ... 
        outputs:
            image-tag: '${{ steps.meta.outputs.tags }}'
      jobs:
    build:
        name: Build & Publish Docker Image
        ... 
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
                jobs:
    build:
        name: Build & Publish Docker Image
        ... 
        steps:
        ...
        - name: Login to Container Registry 
          uses: docker/login-action@v3 
          with:
            registry: '${{ env.REGISTRY }}'
            username: '${{ github.actor }}'
            password: '${{ secrets.GITHUB_TOKEN }}'
            jobs:
    build:
        name: Build & Publish Docker Image
        ... 
        steps:
        ...
        - name: Extract metadata for Docker 
          id: meta
          uses: docker/metadata-action@v4 
          with:
            images: '${{ env.REGISTRY }}/${{ env.APP_NAME }}' 
            tags: |
                type=sha, format=short
                jobs:
    build:
        name: Build & Publish Docker Image
        ... 
        steps:
        ...
        - name: Build and Publish Docker Image 
          uses: docker/build-push-action@v5 
          with:
            context: .
            push: true
            tags: '${{ steps.meta.outputs.tags }}' 
            labels: '${{ steps.meta.outputs.labels }}'
            